name: Feature Request
description: Suggest a new feature or enhancement
title: '[FEATURE] '
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Component
        - New API Endpoint
        - UI/UX Enhancement
        - Performance Improvement
        - Developer Experience
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking my work)
        - High (Very important)
        - Medium (Would be nice to have)
        - Low (Not urgent)
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe how you would use this feature
      placeholder: |
        1. As a [user type]
        2. I want to [action]
        3. So that [benefit]
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: Describe any alternative solutions or features you've considered

  - type: checkboxes
    id: scope
    attributes:
      label: Feature Scope
      description: What areas would this feature affect?
      options:
        - label: Frontend/UI
        - label: Backend/API
        - label: Database
        - label: Authentication
        - label: Documentation
        - label: Testing
        - label: Build/Deploy

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or mockups about the feature request
      placeholder: Any other relevant information

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have clearly described the problem and proposed solution
          required: true
        - label: I am willing to help implement this feature (optional)
          required: false
