name: Question
description: Ask a question about the project
title: '[QUESTION] '
labels: ['question']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question! Please fill out the form below.

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - Getting Started
        - Authentication
        - Database/Prisma
        - API Routes
        - UI/Components
        - Deployment
        - Configuration
        - Best Practices
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Ask your question here...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context or what you've tried so far
      placeholder: |
        - What are you trying to accomplish?
        - What have you tried?
        - Any error messages?

  - type: textarea
    id: code
    attributes:
      label: Relevant Code (if applicable)
      description: Share any relevant code snippets
      render: typescript
      placeholder: |
        // Paste your code here

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have checked the README and documentation
          required: true
        - label: I have searched existing issues and discussions
          required: true
        - label: This is a question, not a bug report or feature request
          required: true
